version: "3.9"

services:
  backend:
    image: breadfan18/grocery-backend
    ports:
      - 4001:3000
    volumes:
      - .:/src/
  frontend:
    build: .
    ports:
      - 4000:3000
    depends_on:
      - backend

volumes:
  mongo_db: {}
