version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  backend:
    image: breadfan18/grocery-backend
    ports:
      - 4001:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Swaroop Uprety
    volumes:
      - .:/src/
  frontend:
    build: .
    ports:
      - 4000:3000
    depends_on:
      - mongo_db
      - backend

volumes:
  mongo_db: {}
